package cn.openwatch.demo;

public enum Feature {
    SEND_DATA, SEND_BITMAP_DATA, SEND_DATAMAP_DATA, SEND_STREAM_DATA, SEND_MSG, SEND_BITMAP_MSG, SEND_DATAMAP_MSG, SEND_STREAM_MSG, SEND_BOTHWAY,  HTTP;

    String name;
}